<?php
// config/kra.php

return [
    'api_sandbox_base_url' => env('KRA_API_SANDBOX_BASE_URL', 'https://etims-api-sbx.kra.go.ke/etims-api/'),
    'api_production_base_url' => env('KRA_API_PRODUCTION_BASE_URL', 'https://etims-api.kra.go.ke/etims-api/'),
    'vscu_jar_base_url' => env('KRA_VSCU_JAR_BASE_URL', 'http://127.0.0.1:8088'), // Default for local VSCU
    'qr_code_base_url' => env('KRA_QR_CODE_BASE_URL', 'https://etims.kra.go.ke/receipt_validation'), // Hypothetical
    'simulation_mode' => env('KRA_SIMULATION_MODE', false),
    'simulation_responses' => env('KRA_SIMULATION_RESPONSES', true),
    
    // Mock Server Configuration
    'mock_server' => [
        'enabled' => env('KRA_MOCK_SERVER_ENABLED', true),
        'base_url' => env('KRA_MOCK_SERVER_URL', 'http://127.0.0.1:8089'),
        'timeout' => env('KRA_MOCK_SERVER_TIMEOUT', 5),
    ],
    
    // Simulation Responses for Reports
    'simulation_responses' => [
        'x_report' => [
            'tradeName' => 'ICORE Test Business',
            'PIN' => 'P123456789Z',
            'date' => '05/01/2025',
            'time' => '14:30:00',
            'reportType' => 'X_DAILY_REPORT',
            'totalSalesAmountNS' => 15000.00,
            'numberOfSalesReceiptsNS' => 25,
            'totalCreditNoteAmountNC' => -500.00,
            'numberOfCreditNotesNC' => 2,
            'taxableAmountA' => 0.00,
            'taxableAmountB' => 12000.00,
            'taxAmountA' => 0.00,
            'taxAmountB' => 1920.00,
            'openingDeposit' => 1000.00,
            'numberOfItemsSold' => 150,
            'numberOfReceiptCopies' => 5,
            'totalReceiptCopiesAmount' => 250.00,
            'numberOfTrainingReceipts' => 3,
            'totalTrainingReceiptsAmount' => 750.00,
            'numberOfProformaReceipts' => 2,
            'totalProformaReceiptsAmount' => 500.00,
            'allDiscounts' => 300.00,
            'otherReductionsAmount' => 0.00,
            'numberOfIncompleteSales' => 1,
        ],
        'z_report' => [
            'tradeName' => 'ICORE Test Business',
            'PIN' => 'P123456789Z',
            'date' => '05/01/2025',
            'time' => '23:59:59',
            'reportType' => 'Z_DAILY_REPORT',
            'totalSalesAmountNS' => 15000.00,
            'numberOfSalesReceiptsNS' => 25,
            'totalCreditNoteAmountNC' => -500.00,
            'numberOfCreditNotesNC' => 2,
            'taxableAmountA' => 0.00,
            'taxableAmountB' => 12000.00,
            'taxAmountA' => 0.00,
            'taxAmountB' => 1920.00,
            'openingDeposit' => 1000.00,
            'numberOfItemsSold' => 150,
            'numberOfReceiptCopies' => 5,
            'totalReceiptCopiesAmount' => 250.00,
            'numberOfTrainingReceipts' => 3,
            'totalTrainingReceiptsAmount' => 750.00,
            'numberOfProformaReceipts' => 2,
            'totalProformaReceiptsAmount' => 500.00,
            'allDiscounts' => 300.00,
            'otherReductionsAmount' => 0.00,
            'numberOfIncompleteSales' => 1,
        ],
        'plu_report' => [
            'companyName' => 'ICORE Test Business',
            'taxIdentificationNumber' => 'P123456789Z',
            'intervalDate' => '20250105',
            'intervalTime' => '143000',
            'reportType' => 'PLU_REPORT',
            'items' => [
                [
                    'itemCode' => 'ITEM001',
                    'itemName' => 'Test Product 1',
                    'unitPrice' => 100.00,
                    'taxRate' => 16.00,
                    'quantitySold' => 50.0,
                    'amountCollected' => 5800.00,
                    'remainQuantityInStock' => 150.0,
                ],
                [
                    'itemCode' => 'ITEM002',
                    'itemName' => 'Test Product 2',
                    'unitPrice' => 75.00,
                    'taxRate' => 16.00,
                    'quantitySold' => 30.0,
                    'amountCollected' => 2610.00,
                    'remainQuantityInStock' => 70.0,
                ],
                [
                    'itemCode' => 'ITEM003',
                    'itemName' => 'Test Product 3',
                    'unitPrice' => 200.00,
                    'taxRate' => 0.00,
                    'quantitySold' => 25.0,
                    'amountCollected' => 5000.00,
                    'remainQuantityInStock' => 75.0,
                ],
            ],
        ],
    ],
];
